version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "6e:06:f5:6e:13:a8:3f:a2:1d:69:8d:47:0e:44:1e:75"
      - run:
          name: exec script
          command: .circleci/deploy_test.sh
